[pytest]

; щоб працював `pytest`, а не тільки `python -m pytest`
pythonpath = .

addopts =
    --strict-markers
    --tb=short
    -v

markers =
    db: тести роботи з базою даних
    app: тести логіки додатку
