[pytest]

; щоб працював `pytest`, а не тільки `python -m pytest`
pythonpath = .

addopts =
    --strict-markers
    --tb=short
    -v

markers =
    ui: ui tests for qauto2 registration
    positive: positive scenarios
    negative: negative scenarios
