[pytest]

; щоб працював `pytest`, а не тільки `python -m pytest`
pythonpath = .

addopts =
    --strict-markers
    --tb=short
    -v
    --alluredir=allure-results
    --clean-alluredir
    --html=report.html
    --self-contained-html

markers =
    ui: ui tests for qauto2 registration
    positive: positive scenarios
    negative: negative scenarios
